.PHONY: build test clean serve assets rocq-build ocaml-build

# Path to the Q3 Arena Demo installer or pak0.pk3.
# Set on the command line: make assets DEMO=/path/to/Q3ADemo.exe
DEMO ?=

EXTRACT_BIN = extract_assets/extract-assets

build: rocq-build ocaml-build

rocq-build:
	rocq compile -Q theories Hello theories/Hello.v
	rocq compile -Q theories Hello theories/ExtractAssets.v

# extract_assets_core.{ml,mli} are generated by rocq-build via the Extraction
# command in theories/ExtractAssets.v.  Compile from inside the directory so
# that .cmi files land alongside their .mli counterparts.
ocaml-build: rocq-build
	cd extract_assets && \
	    ocamlfind ocamlopt -package camlzip,unix -c extract_assets_core.mli && \
	    ocamlfind ocamlopt -package camlzip,unix -c extract_assets_core.ml && \
	    ocamlfind ocamlopt -package camlzip,unix -c main.ml && \
	    ocamlfind ocamlopt -package camlzip,unix -linkpkg \
	        extract_assets_core.cmx main.cmx -o extract-assets

test: build

clean:
	rm -f theories/*.vo theories/*.vok theories/*.vos theories/*.glob theories/.*.aux
	rm -f extract_assets/extract_assets_core.ml extract_assets/extract_assets_core.mli
	rm -f extract_assets/*.cm{i,o,x} extract_assets/*.o
	rm -f $(EXTRACT_BIN)

assets: $(EXTRACT_BIN)
	@test -n "$(DEMO)" || { \
	  printf 'error: DEMO is not set.\n'; \
	  printf 'Usage: make assets DEMO=/path/to/installer-or-pak0.pk3\n'; \
	  printf '\n'; \
	  printf 'DEMO can be:\n'; \
	  printf '  The Linux installer:   linuxq3ademo-1.11-6.x86.gz.sh\n'; \
	  printf '  The Windows installer: Q3ADemo.exe\n'; \
	  printf '  A bare pak0.pk3:       demoq3/pak0.pk3\n'; \
	  printf '\nSee README.md and ASSETS.md for details.\n'; \
	  exit 1; \
	}
	$(EXTRACT_BIN) --output docs/assets "$(DEMO)"

serve:
	@test -d docs/assets || { \
	  printf 'warning: docs/assets/ not found — game assets will not load.\n'; \
	  printf 'Run: make assets DEMO=/path/to/installer-or-pak0.pk3\n'; \
	  printf 'See README.md for details.\n'; \
	}
	python3 -m http.server 8080 --directory docs
